### ISSUE TITLE
Model response returns entered prompt 

### ISSUE THREAD

**Issue by AdiM10root** [dfinke/PSAI#10]
when running the following:
Install-Module -Name PSAI -Scope CurrentUser -Force
$env:OpenAIKey = "*******************************************" #replaced with my valid API Key
Invoke-OAIChat -UserInput "what is the weather for today?"

I'm getting the following reply:
what is the weather for today?

any question i ask, i get a reply with my original question:
![invoke-oaichat example](https://github.com/dfinke/PSAI/assets/68636014/319928c5-2bce-47a4-95b8-14769d27bb49)

**Comment by dfinke** [comment]
Some folks get that. I cannot reproduce.

Have you had your account for a while? Did you add $ and buy credits?
https://github.com/dfinke/PSAI/issues/5#issuecomment-2108939759

**Comment by AdiM10root** [comment]
I have toped-up the API credit and it solved the issue.

Closed.

**Comment by dfinke** [comment]
A new version of PSAI is imminent. This was dropping the 'quota max reached' and should be fixed.
