### ISSUE TITLE
Getting only the question text back as the answer

### ISSUE THREAD

**Issue by TechLinkRon** [dfinke/PSAI#14]
I think I must have missed a basic step of my setup somehow.  I got around my initial "The requested model 'gpt-4o' does not exist." error via the "-model" option, but now I just get my question returned to me:

![image](https://github.com/dfinke/PSAI/assets/17254873/de41ed7f-a1b1-4f44-a18e-d9a298edad24)

**Comment by dfinke** [comment]
Seems like you set your OpenAI key in the $env. Do you add credits to it?
