### ISSUE TITLE
New-OAIThread is not recognized as a cmdlet

### ISSUE THREAD

**Issue by Rorymon** [dfinke/PSAI#16]
'New-OAIThread' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by Rorymon** [comment]
Apologies, I should have added that I received this when trying the example cmdlet in the documentation. This is on a Windows 10 machine that did have the PowerShellAI Module previously. It appears that the new module did install and I see the New-OAIThread.ps1 file but the call to New-OAIThread results in the above error. The cmdlet also does not appear to be found in a regular PowerShell window.

**Comment by dfinke** [comment]
Thanks for trying this out. The `PowerShellAI` module has been replaced by this new one `PSAI` which is more advanced version.

Please:
1. `Uninstall-Module PowerShellAI`
2. `Install-Module PSAI`

**Comment by Rorymon** [comment]
Unfortunately, it appears to still fail after explicitly uninstalling and installing the new module. I also tried on a VM that never had PowerShellAI installed.

As you can see, it appears the script for New-OAIThread does exist but Invoke-OAIChat, ai or some of the other cmdlets fail.

![AIError](https://github.com/dfinke/PSAI/assets/7652987/8400cf52-c3b1-4bce-95b9-916fd404b066)

cmdlets and error:
PS C:\Windows\system32> $env:OpenAIKey = '<APIKeyRemovedtoProtectit>'
PS C:\Windows\system32> ai "What is TechSmith Camtasia in 30 words or less."
New-OAIThread : The term 'New-OAIThread' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\PSAI\0.2.1\Public\New-OAIThreadQuery.ps1:33 char:15
+     $thread = New-OAIThread
+               ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-OAIThread:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Unknown parameter: 'content'.
At C:\Program Files\WindowsPowerShell\Modules\PSAI\0.2.1\Private\Invoke-OAIBeta.ps1:137 char:9
+         throw $targetError
+         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unknown parameter: 'content'.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unknown parameter: 'content'.

**Comment by dfinke** [comment]
Bummer, works for me

```powershell
PS C:\> ai "What is TechSmith Camtasia in 30 words or less."
TechSmith Camtasia is a software suite for creating video tutorials and presentations via screencast or direct recording. It offers video editing, audio enhancement, and interactive elements to enhance multimedia content.
```

## Try

```powershell
Uninstall-Module PSAI
Uninstall-Module PowerShellAI.Functions

Install-Module PSAI
```

I think you installed a later `PowerShellAI` when I started expanding it to do Function Calling.

If that doesn't work, happy to get on a zoom and walk thru to see the  issue.

**Comment by Rorymon** [comment]
If you have the time for a Zoom call that would be awesome, I can snapshot the VM and park it for now. If you are off this week for the holiday, no sweat.

**Comment by adenyes** [comment]
I had this same issue. I see that the problem was that this module was written for PowerShell 7+, but I was misled by the listing on powershellgallery, which claims minimum version is 5.1
https://www.powershellgallery.com/packages/PSAI/0.2.7

**Comment by dfinke** [comment]
@adenyes  Next release will update the PowerShell Gallery that minimum version is 7+.
