### ISSUE TITLE
Invoke-OAIChat command repeats the question asked.

### ISSUE THREAD

**Issue by ljfp** [dfinke/PSAI#27]
```
PS C:\Users\ljfp> Invoke-OAIChat 'How do I output all files in a directory PowerShell?'
How do I output all files in a directory PowerShell?
```

```
PS C:\Users\ljfp> Invoke-OAIChat 'How do I create a new profile in PowerShell 7?'
How do I create a new profile in PowerShell 7?
```

This is a fresh installation of PSAI, and the API key is set in the environment variable 'OpenAIKey'

I'm not sure where to start troubleshooting this.

**Comment by ljfp** [comment]
Other examples of this behaviour:

```
PS C:\Users\ljfp> Invoke-OAIChat -UserInput "What is the weather today?"
What is the weather today?
```

```
PS C:\Users\ljfp> 'show even numbers' | ai -Instructions 'use powershell, just code, no explanation'
show even numbers
```

**Comment by ljfp** [comment]
My bad, it seems that I had run out of credits, and I didn't realize. I wasn't aware that OpenAI API just echoes your input once you reach $0.

**Comment by dfinke** [comment]
@ljfp Thanks for trying PSAI. I'm surprised you didn't get a message that the balance was $0.

What version of PSAI is installed?

`Get-Module -list PSAI`

Also check out my latest short video on using the features of the module:
https://youtu.be/r_yC3dBe6lA

If you like it 👍🏼and subscribe

Lastly, I did a livestream on PSAI and my upcoming PSAIAgent module.
If you subscribe to my YouTube channel, you'll get notified when I post this and other videos.

https://www.meetup.com/NycPowershellMeetup/events/302619165
