### ISSUE TITLE
Using Azure OpenAI failed on Invoke-OAIChat

### ISSUE THREAD

**Issue by darthmuffin000** [dfinke/PSAI#29]
Hi, 

Followed your install and setup for PSAI.

I've setup my Azure OpenAI Service and also deployed a working endpoint for gpt-4 through Azure OpenAI Studio.
I even tested the web chat with my deployment and it worked.

Not Working: 
From your PSAI for Azure OpenAI setup page, I used your powershell test and got this error:
-----------------------------------------------------------------------
PS C:\Users\me> $secrets = @{
>>     apiURI         = "https://my-azure-openai-service.openai.azure.com/openai/deployments/my-deployed-model-name/chat/completions?api-version=2023-03-15-preview"
>>     apiVersion     = "2023-03-15-preview"
>>     apiKey         = "my-actual-api-key-here"
>>     deploymentName = "my-deployed-model-name"
>> }
PS C:\Users\me> Set-OAIProvider AzureOpenAI
PS C:\Users\me> Set-AzOAISecrets @secrets
PS C:\Users\me> Invoke-OAIChat 'How do I output all files in a directory PowerShell?'
Exception: C:\Users\me\OneDrive\Documents\PowerShell\Modules\PSAI\0.2.9\Private\Invoke-OAIBeta.ps1:137
Line |
 137 |          throw $targetError
     |          ~~~~~~~~~~~~~~~~~~
     | Response status code does not indicate success: 404 (Resource Not Found).

Working: 
I have been doing tests by invoking my endpoint through standard powershell commands and the AI API service answered correctly.
----------------------------------------------------------------
PS C:\Users\me> # Store the correct target URI and API key
PS C:\Users\me> $uri = "https://my-azure-openai-service.openai.azure.com/openai/deployments/my-deployed-model-name/chat/completions?api-version=2023-03-15-preview"
PS C:\Users\me> $apiKey = "my-actual-api-key-here"
PS C:\Users\me>
PS C:\Users\me> # Set up headers with the API key for authorization
PS C:\Users\me> $headers = @{
>>     "api-key" = $apiKey
>>     "Content-Type" = "application/json"
>> }
PS C:\Users\me> # Define a minimal payload for the POST request
PS C:\Users\me> $body = @{
>>     "messages" = @(
>>         @{
>>             "role" = "user"
>>             "content" = "Hello, OpenAI!"
>>         }
>>     )
>> } | ConvertTo-Json
PS C:\Users\me> # Perform a POST request
PS C:\Users\me> try {
>>     $response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body
>>     Write-Host "POST request successful. Response:" -ForegroundColor Green
>>     $response
>> } catch {
>>     Write-Host "Error with POST request:" $_.Exception.Message -ForegroundColor Red
>> }

POST request successful. Response:

choices            : {@{finish_reason=stop; index=0; message=}}
created            : 1725664070
id                 : chatcmpl-A4cLOhbhs436gfsddsfdeAyWwNAkSl1br
model              : gpt-4
object             : chat.completion
system_fingerprint :
usage              : @{completion_tokens=9; prompt_tokens=12; total_tokens=21}

I don't know what else I can setup to make it work through my Azure OpenAI API.

Thanks for your help on this.

(btw, what you have built seem awesome, can't wait to use it! :-) )

**Comment by dfinke** [comment]
you need to set up the parameters similar to this.

the `apiversion ` may be newer.

```powershell
$secrets = @{
    apiURI         = "https://openai-gpt-latest.openai.azure.com"
    apiVersion     = "2024-02-15-preview"
    apiKey         = "70ezzzz1f1ad4czzzzzz3a320dbxxxx"
    deploymentName = "gpt4-latest"
}

Set-OAIProvider AzureOpenAI
Set-AzOAISecrets @secrets
```
