### ISSUE TITLE
URI Address - how to change ?

### ISSUE THREAD

**Issue by tupiacy** [dfinke/PSAI#34]
Hello.
This may be a stupid question. I was provided with a dedicated URI address along with an API key. For PSAI is there any possibility to change URI address? I see that only the official OpenAI is supported  and there is no possibility to change it.

Thank you :)

**Comment by dfinke** [comment]
Hmm, not stupid. There is no way to do that externally.

Is that a corporate or team URI? Or is it to Azure OpenAI?

You could install the PSAI module, locat the `PSAI.psm1` and chabge `$script:baseUrl = "https://api.openai.com/v1"` to your URI.

**Comment by tupiacy** [comment]
It is corporate URI and connected to Azure OpenAI. As I mentioned early have received for tests only URI and API but without any more details to connect as a AzureOpenAI option. 

I will try your tip.

Thank you

**Comment by dfinke** [comment]
Since you are using Azure OpenAI there is an external way to change that.

[Here are the instructions](https://github.com/dfinke/PSAI/?tab=readme-ov-file#support-for-azure-openai)

**Comment by dfinke** [comment]
@andynousiainen understood. you are comfortable having the Azure apiKey in a `$env`?

Let me think about it. I am planning some changes for the Azure setup.
