### ISSUE TITLE
Should not found type translations default to object?

### ISSUE THREAD

**Issue by dfinke** [dfinke/PSAI#41]
@Agazoth 

Or should it throw?

I think defaulting the data type to object is preferred.
Otherwise this would "fail" with in strange ways when called.

Thoughts?

![image](https://github.com/user-attachments/assets/fa49ee38-45f6-48d1-bd8c-5d2e24992810)

**Comment by dfinke** [comment]
Going to work on this:

![image](https://github.com/user-attachments/assets/2de4a7c1-d82b-461f-adaa-641b70b9d033)

**Comment by Agazoth** [comment]
Running this on experimental P+M branch:
```powershell
$tools = @(Register-Tool gc -WarningAction SilentlyContinue; Register-Tool ls -WarningAction SilentlyContinue)
$Agent = New-Agent -Instructions "Path = C:\temp\TestData\" -Tools $tools -ShowToolCalls
$Agent | Invoke-InteractiveCLI
```

<img width="702" alt="{744BCF84-A38A-45FA-9A97-7DAA61700543}" src="https://github.com/user-attachments/assets/948c3d5f-13ee-4a3d-8f8c-a6307a4cb05f">

**Comment by Agazoth** [comment]
And:
<img width="582" alt="{DE1D2E59-5AE6-4D7C-AEC3-ECB62E1CD21F}" src="https://github.com/user-attachments/assets/cd575e71-f782-4ee1-86f9-57c5b601e1a7">

**Comment by dfinke** [comment]
Thank you!

Revolved in https://github.com/dfinke/PSAI/pull/42
