### ISSUE TITLE
How do I configure the temperature, max_tokens, and top_p parameters using the PowerShell command Invoke-OAIChat?

### ISSUE THREAD

**Issue by EelcoLabordus** [dfinke/PSAI#43]
Hi everyone,

I'm currently using the Invoke-OAIChat command in PowerShell to interact with the Azure OpenAI API. I would like to know how to configure the temperature, max_tokens, and top_p parameters to control the randomness, length, and nucleus sampling of the responses, respectively. Could someone provide an example of how to set these parameters within the command?

Thanks in advance for your help!

**Comment by dfinke** [comment]
@EelcoLabordus Thanks for tryong PSAI. Does `Invoke-OAIChatCompletion` work for you? I has those parameters.
