### ISSUE TITLE
API Key reset after Invoke-Pester

### ISSUE THREAD

**Issue by dfinke** [dfinke/PSAI#50]
@Agazoth - I ran the tests from the cli and then did `q` to the model. I get this error.

It'd be optimal if the env is set to where it was before running tests. Something to keep in mind.

Workaround, run tests in a separate console.

![image](https://github.com/user-attachments/assets/cbf46a3e-1738-42f0-be7a-e914fce49670)

**Comment by Agazoth** [comment]
@dfinke  fix provided - saving current key before test and resetting after test

**Comment by Agazoth** [comment]
Added s cmdlet to remove the AIProviderList and added that to the tests. Should be good now

**Comment by dfinke** [comment]
worked!
