### ISSUE TITLE
 New-ProviderListFromEnv - Provider already exists in the list. Use -Force to overwrite

### ISSUE THREAD

**Issue by dfinke** [dfinke/PSAI#58]
New-ProviderListFromEnv doesn't have a `-Force` switch
![image](https://github.com/user-attachments/assets/5bb95f7f-93a3-4be4-ad07-cdeb549db588)

Nice to have - don't terminate on error, issue warning

Then it could process all providers in the env.

**Comment by Agazoth** [comment]
It is an private function and not ment to be used in workflow.
![image](https://github.com/user-attachments/assets/c3a2f929-b60f-4fd0-8773-a7ac001af28b)


If it has been triggered at some point, it has added a provider to the providerlist. From there the Set-AIProvider, Get-AIProvider, Clear-ProviderList, New-AIProvider, Import-AIProvider should be sufficient to handle changes.

**Comment by Agazoth** [comment]
https://github.com/dfinke/PSAI/pull/48/commits/9ff15ed65adc8a9f27bdac09b2a0a643c75090fe
