### ISSUE TITLE
PShell `q` fails

### ISSUE THREAD

**Issue by dfinke** [dfinke/PSAI#61]
I didn't see a PR for the PShell repo. I  haven't pull over that functionality yet.

![image](https://github.com/user-attachments/assets/e4114914-eb8e-4b26-8695-5b84a167c7e4)

**Comment by Agazoth** [comment]
Ahh, I hacked that im my local installation. You just need `$agentResponse = $agent | Get-AgentResponse $prompt` in that line in `PShell-AI\0.2.4\Public\q.ps1` when using PSAI 0.4.0
![image](https://github.com/user-attachments/assets/9c3d602c-ab18-4787-ba6f-a8a0c46182cb)

This will only work with PSAI 0.4.0 and abobe :-)

**Comment by Agazoth** [comment]
Works with the q added to the PR :-)
