### ISSUE TITLE
Exception calling "PrintResponse"

### ISSUE THREAD

**Issue by dfinke** [dfinke/PSAI#62]
Also: Let's check the ApiKey type, if it is a string convert it to a secure string

```powershell
$params = @{
    Provider = 'Anthropic'
    # ApiKey   = Get-Secret -Name AnthropicCAPI
    # ApiKey   = $env:AnthropicAPIKey
    ApiKey   = ConvertTo-SecureString $env:AnthropicAPIKey -AsPlainText
}

Import-AIProvider @params -Default

New-Agent | Get-AgentResponse 'what is the capital of france'
```

![image](https://github.com/user-attachments/assets/85c4e7de-192d-4a9d-ae03-1a498076830a)

**Comment by Agazoth** [comment]
@dfinke I cannot reproduce this.
![{8EA29AE4-F5D3-43E6-9F68-518A5D9AFBA2}](https://github.com/user-attachments/assets/aef92116-d10f-440c-beed-f5f7e0506342)

**Comment by dfinke** [comment]
i did mine in vscode. could be some setting there

**Comment by Agazoth** [comment]
Works now
