### ISSUE TITLE
Vault Microsoft.PowerShell.SecretStore requires a password

### ISSUE THREAD

**Issue by dfinke** [dfinke/PSAI#67]
Pulled latest and installed the module locally.

![image](https://github.com/user-attachments/assets/74a641d1-f596-45b7-a180-f852cf873aa6)

**Comment by Agazoth** [comment]
This is not really a bug, but a feature. If no env keys are configured, the code will invoke Microsoft.PowerShell.SecretManagent to get the Api keys for the 4 built-in commercial providers.

SecretStore is just one of many extensions for SecretManagenent. It requires a password. Give it a password and the code will run.

If users have setup Microsoft.PowerShell.SecretManagent, they will be accustomed to this behavior.

Would you prefer that Microsoft.PowerShell.SecretManagent would require the end user to actively opt-in to activate?

**Comment by dfinke** [comment]
Absolutely, yes, please.

> 'Would you prefer that Microsoft.PowerShell.SecretManagent would require the end user to actively opt-in to activate?'

The user should be able to install the module, set the OpenAI API Key env var and it just works.

None of the providers or SDK ports (there may be an exception) do anything around secret managenent or obfuscation of the key.

It is nice to have, not a requirement and not turned on by default.

The fewest steps to get up and running with PSAI is the goal.

**Comment by Agazoth** [comment]
Microsoft.PowerShell.SecretManagent is now fully optional
