### ISSUE TITLE
What happened to the PowerShellAI module?

### ISSUE THREAD

**Issue by mikenelson-io** [dfinke/PSAI#7]
Existing scripts use the syntax from PowerShellAI module. PSAI is all new cmdlet naming.
What happened?

**Comment by dfinke** [comment]
Sorry, OpenAI has been churning for the last 1.5 years. They changed many things. Including how worked with their backend. 
PSAI is my way forward. Even the new things OpenAI dropped last November are being sunset end of the year.

What functions were you calling that are not in PSAI?

**Comment by mikenelson-io** [comment]
The code was for demos used in my AI presentations that highlight Copilot and PowerShellAI.
Basically, I was showing off your module as part of it.
________________________________
