### ISSUE TITLE
Out of the box Gemini is the default 

### ISSUE THREAD

**Issue by dfinke** [dfinke/PSAI#70]
I deleted and re-installed PSAI. OpenAI did not come up as the default. I used the `Set-AIDefault 'openai:gpt-4o-mini'`, it works. If I `ipmo psai -force` psai reverts to Gemini as the default.

![image](https://github.com/user-attachments/assets/d9bbdbe8-7dbb-4b66-9ecb-ada1d67b7d54)

**Comment by dfinke** [comment]
thought that may be it. having to set that each time in the $PROFILE seems not optimal.

**Comment by Agazoth** [comment]
Now OpenAI is the default if multiple providers are configured in at first run
