### ISSUE TITLE
Assistant interface - messages: Field required

### ISSUE THREAD

**Issue by dfinke** [dfinke/PSAI#74]
Probably a side effect of the messages being updated.

![image](https://github.com/user-attachments/assets/c7e2d4c4-6efa-472f-a2ea-c07dec5511de)

**Comment by Agazoth** [comment]
Cmdlets updated to support new ProviderModel setup

**Comment by dfinke** [comment]
the model isn't working out
![image](https://github.com/user-attachments/assets/a2e81095-d7a8-4e15-83dc-28851e8a01d5)
