### ISSUE TITLE
OpenAI o1-preview - Messages role does not support system

### ISSUE THREAD

**Issue by dfinke** [dfinke/PSAI#79]
Excpected it to fail sending a system message and then would try setting user etc.

![image](https://github.com/user-attachments/assets/b822f67a-accb-4d88-b8d1-18803826b007)

![image](https://github.com/user-attachments/assets/f0f85be9-058b-4b8b-afab-e4ae5f56eccb)

**Comment by Agazoth** [comment]
Seems system messages are being deprected and replaced by developer messages.  This is a breakting change for all that use the new endpoints.
<img width="485" alt="{B720BC4F-D1F7-42C1-B917-BFD1FBEAB963}" src="https://github.com/user-attachments/assets/2fa9a6ad-ecff-40b8-af97-0da543480b60" />

This emphazises the need for moving message handeling to the Providers.

We might need a bigger feature for that. dEverything that goes in the body of an endpoint invoke, should be handled by the provider. That is Messages, Tools/Functions, Threads etc. 

I can do a loop for this specific errorcode and replace system with developer for now

**Comment by Agazoth** [comment]
Or maybe not!
<img width="673" alt="{BD6F3EA0-13C2-428F-955E-F93D029777FD}" src="https://github.com/user-attachments/assets/33fb3ffb-b849-4aaa-b50b-07533e6c2332" />

Not supported for now: https://community.openai.com/t/o1-preview-not-working-in-api-tier-1/1025971

Seems the solution is to just drop the system message.

**Comment by dfinke** [comment]
Sounds good. They have introduced a `developer` message. Don't know if o1 supports it or it is only fo o3 and forward for now.
